# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine
WORKDIR /app

# Copy package and source
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
COPY examples ./examples

# Install dependencies and build
RUN npm install && npm run build && npm prune --production

# Default command entrypoint
CMD ["node", "dist/cli.js"]
